/**
 * Memory files service.
 *
 * Provides filesystem scanning and file I/O for agent memory files (.md).
 * Used by the Memory tab API routes to list, read, and write markdown files
 * in an agent's workspace directory.
 *
 * All path operations use resolveWithin() for traversal safety.
 */

import fs from 'node:fs'
import path from 'node:path'
import { resolveWithin } from '@/lib/paths'

/**
 * Represents a file or directory node in the workspace tree.
 */
export interface MemoryFileNode {
  /** Relative path from workspace root, e.g. "SOUL.md" or "memory/MEMORY.md" */
  path: string
  /** Filename only, e.g. "SOUL.md" */
  name: string
  /** Whether this node is a file or directory */
  type: 'file' | 'directory'
  /** Last modified timestamp in Unix milliseconds (files only) */
  modified?: number
  /** True for auto-generated files that should not be edited (HEARTBEAT.md, SESSION-STATE.md) */
  readOnly?: boolean
  /** Child nodes (directories only) */
  children?: MemoryFileNode[]
}

/** Files that are auto-generated by the agent and should not be edited via the dashboard */
export const READ_ONLY_FILES = new Set(['HEARTBEAT.md', 'SESSION-STATE.md'])

/**
 * Recursively scan a workspace directory for .md files.
 *
 * Returns a tree of MemoryFileNode objects. Directories that contain
 * no .md files (at any depth) are excluded. Dotfiles and dotdirs are skipped.
 * Results are sorted: directories first, then files, alphabetical within each group.
 */
export function scanWorkspace(workspacePath: string): MemoryFileNode[] {
  return scanDir(workspacePath, workspacePath)
}

function scanDir(dirPath: string, workspaceRoot: string): MemoryFileNode[] {
  let entries: fs.Dirent[]
  try {
    entries = fs.readdirSync(dirPath, { withFileTypes: true })
  } catch {
    return []
  }

  const nodes: MemoryFileNode[] = []

  for (const entry of entries) {
    // Skip dotfiles and dotdirs
    if (entry.name.startsWith('.')) continue

    const fullPath = path.join(dirPath, entry.name)
    const relPath = path.relative(workspaceRoot, fullPath)

    if (entry.isFile() && entry.name.endsWith('.md')) {
      try {
        const stat = fs.statSync(fullPath)
        nodes.push({
          path: relPath,
          name: entry.name,
          type: 'file',
          modified: stat.mtimeMs,
          readOnly: READ_ONLY_FILES.has(entry.name) || undefined,
        })
      } catch {
        // Skip files that can't be stat'd
      }
    } else if (entry.isDirectory()) {
      const children = scanDir(fullPath, workspaceRoot)
      // Only include directories that contain .md files (at any depth)
      if (children.length > 0) {
        nodes.push({
          path: relPath,
          name: entry.name,
          type: 'directory',
          children,
        })
      }
    }
  }

  // Sort: directories first, then files, alphabetical within each group
  return nodes.sort((a, b) => {
    if (a.type !== b.type) return a.type === 'directory' ? -1 : 1
    return a.name.localeCompare(b.name)
  })
}

/**
 * Read a memory file's content and metadata.
 *
 * Uses resolveWithin() to prevent path traversal. Returns null if the file
 * does not exist. Throws if the path attempts to escape the workspace.
 */
export function readMemoryFile(
  workspacePath: string,
  filePath: string
): { content: string; modified: number; readOnly: boolean } | null {
  const safePath = resolveWithin(workspacePath, filePath)

  try {
    const content = fs.readFileSync(safePath, 'utf-8')
    const stat = fs.statSync(safePath)
    return {
      content,
      modified: stat.mtimeMs,
      readOnly: READ_ONLY_FILES.has(path.basename(filePath)),
    }
  } catch (err: unknown) {
    // File doesn't exist or can't be read
    if (err && typeof err === 'object' && 'code' in err && err.code === 'ENOENT') {
      return null
    }
    throw err
  }
}

/**
 * Write content to a memory file.
 *
 * Uses resolveWithin() to prevent path traversal. Throws if:
 * - The path attempts to escape the workspace
 * - The file is in READ_ONLY_FILES (HEARTBEAT.md, SESSION-STATE.md)
 *
 * Creates the file if it does not exist (in an existing directory).
 */
export function writeMemoryFile(
  workspacePath: string,
  filePath: string,
  content: string
): { modified: number } {
  // Check read-only before resolving path
  if (READ_ONLY_FILES.has(path.basename(filePath))) {
    throw new Error(`File is read-only: ${path.basename(filePath)}`)
  }

  const safePath = resolveWithin(workspacePath, filePath)
  fs.writeFileSync(safePath, content, 'utf-8')

  return { modified: Date.now() }
}
