'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import { cn } from '@/lib/utils'
import { MarkdownRenderer } from '@/components/markdown-renderer'
import { useToast } from '@/components/ui/toast-provider'

interface MemoryFileEditorProps {
  agentId: string
  filePath: string | null
  isViewer: boolean
  isAgentRunning: boolean
  onDirtyChange?: (dirty: boolean) => void
}

export function MemoryFileEditor({
  agentId,
  filePath,
  isViewer,
  isAgentRunning,
  onDirtyChange,
}: MemoryFileEditorProps) {
  const { show: showToast } = useToast()

  const [content, setContent] = useState('')
  const [originalContent, setOriginalContent] = useState('')
  const [mode, setMode] = useState<'preview' | 'edit'>('preview')
  const [readOnly, setReadOnly] = useState(false)
  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const [fileName, setFileName] = useState('')

  const isDirty = content !== originalContent

  // Track dirty state for parent
  const prevDirtyRef = useRef(false)
  useEffect(() => {
    if (prevDirtyRef.current !== isDirty) {
      prevDirtyRef.current = isDirty
      onDirtyChange?.(isDirty)
    }
  }, [isDirty, onDirtyChange])

  // Fetch file content when filePath changes
  useEffect(() => {
    if (!filePath) {
      setContent('')
      setOriginalContent('')
      setMode('preview')
      setReadOnly(false)
      setFileName('')
      return
    }

    setLoading(true)
    setMode('preview')
    const name = filePath.split('/').pop() || filePath
    setFileName(name)

    fetch(`/api/agents/${agentId}/files/${filePath}`)
      .then((res) => {
        if (!res.ok) throw new Error('Failed to load file')
        return res.json()
      })
      .then((data: { content: string; readOnly: boolean }) => {
        setContent(data.content)
        setOriginalContent(data.content)
        setReadOnly(data.readOnly ?? false)
      })
      .catch(() => {
        setContent('')
        setOriginalContent('')
        showToast({ message: 'Failed to load file', type: 'error' })
      })
      .finally(() => setLoading(false))
  }, [agentId, filePath, showToast])

  // Save handler
  const handleSave = useCallback(async () => {
    if (!filePath || !isDirty || saving || isViewer || readOnly) return

    setSaving(true)
    try {
      const res = await fetch(`/api/agents/${agentId}/files/${filePath}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ content }),
      })
      if (!res.ok) throw new Error('Save failed')
      setOriginalContent(content)
      showToast({ message: 'Saved', type: 'success' })
    } catch {
      showToast({ message: 'Failed to save', type: 'error' })
    } finally {
      setSaving(false)
    }
  }, [agentId, filePath, content, isDirty, saving, isViewer, readOnly, showToast])

  // Ctrl+S / Cmd+S keyboard shortcut
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 's') {
        e.preventDefault()
        handleSave()
      }
    }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [handleSave])

  // Empty state
  if (!filePath) {
    return (
      <div className="flex-1 flex items-center justify-center p-4">
        <p className="text-xs text-muted-foreground/60">Select a file to view</p>
      </div>
    )
  }

  // Loading state
  if (loading) {
    return (
      <div className="flex-1 flex items-center justify-center p-4">
        <div className="w-4 h-4 border-2 border-primary/30 border-t-primary rounded-full animate-spin" />
      </div>
    )
  }

  const canEdit = !isViewer && !readOnly

  return (
    <div className="flex flex-col h-full">
      {/* Header bar */}
      <div className="flex items-center gap-2 px-3 py-2 border-b border-border shrink-0">
        <div className="flex items-center gap-1.5 flex-1 min-w-0">
          <span className="text-sm font-medium text-foreground truncate">{fileName}</span>
          {isDirty && (
            <span className="w-1.5 h-1.5 rounded-full bg-warning shrink-0" title="Unsaved changes" />
          )}
          {readOnly && (
            <div className="flex items-center gap-1 text-muted-foreground/60 shrink-0">
              <svg viewBox="0 0 16 16" fill="currentColor" className="w-3 h-3">
                <path d="M8 1a3 3 0 00-3 3v2H4a1 1 0 00-1 1v7a1 1 0 001 1h8a1 1 0 001-1V7a1 1 0 00-1-1h-1V4a3 3 0 00-3-3zm-1.5 3a1.5 1.5 0 013 0v2h-3V4z" />
              </svg>
              <span className="text-[10px]">Auto-generated by agent</span>
            </div>
          )}
        </div>

        {/* Mode toggle */}
        <div className="flex items-center gap-1 shrink-0">
          <button
            onClick={() => setMode('preview')}
            className={cn(
              'px-2 py-0.5 text-[11px] rounded-full transition-colors',
              mode === 'preview'
                ? 'bg-muted text-foreground'
                : 'text-muted-foreground hover:text-foreground'
            )}
          >
            Preview
          </button>
          {canEdit && (
            <button
              onClick={() => setMode('edit')}
              className={cn(
                'px-2 py-0.5 text-[11px] rounded-full transition-colors',
                mode === 'edit'
                  ? 'bg-muted text-foreground'
                  : 'text-muted-foreground hover:text-foreground'
              )}
            >
              Edit
            </button>
          )}
        </div>

        {/* Save button */}
        {mode === 'edit' && canEdit && (
          <button
            onClick={handleSave}
            disabled={!isDirty || saving}
            className={cn(
              'px-2.5 py-1 text-[11px] rounded-md transition-colors shrink-0',
              isDirty && !saving
                ? 'bg-primary text-primary-foreground hover:bg-primary/90'
                : 'bg-muted text-muted-foreground cursor-not-allowed'
            )}
          >
            {saving ? 'Saving...' : 'Save'}
          </button>
        )}
      </div>

      {/* Running agent warning */}
      {isAgentRunning && mode === 'edit' && (
        <div className="mx-3 mt-2 bg-warning/10 border border-warning/30 text-warning text-xs p-2 rounded-md">
          Agent is running -- changes may be overwritten by the agent
        </div>
      )}

      {/* Content area */}
      <div className="flex-1 overflow-y-auto p-3">
        {mode === 'preview' ? (
          <MarkdownRenderer content={content} />
        ) : (
          <textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            className="w-full h-full min-h-[200px] bg-transparent text-sm text-foreground font-mono resize-none p-2 focus:outline-none"
            spellCheck={false}
          />
        )}
      </div>
    </div>
  )
}
