import { NextRequest, NextResponse } from 'next/server'
import { requireRole } from '@/lib/auth'
import { readLimiter, mutationLimiter } from '@/lib/rate-limit'
import { healthMonitor } from '@/lib/health-monitor'
import { readMemoryFile, writeMemoryFile } from '@/lib/memory-files'
import { logger } from '@/lib/logger'

/**
 * GET /api/agents/[id]/files/[...path]
 *
 * Returns the content of a specific .md file from an agent's workspace.
 * Requires viewer role (any authenticated user can read).
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string; path: string[] }> }
) {
  const auth = requireRole(request, 'viewer')
  if ('error' in auth) return NextResponse.json({ error: auth.error }, { status: auth.status })

  const limited = readLimiter(request)
  if (limited) return limited

  try {
    const resolvedParams = await params
    const agentId = resolvedParams.id
    const filePath = resolvedParams.path.join('/')

    const snapshot = healthMonitor.getSnapshot()
    const agent = snapshot.find(a => a.id === agentId)
    if (!agent) {
      return NextResponse.json(
        { error: 'Agent not found or not yet discovered' },
        { status: 404 }
      )
    }

    const result = readMemoryFile(agent.agent.workspacePath, filePath)
    if (!result) {
      return NextResponse.json({ error: 'File not found' }, { status: 404 })
    }

    return NextResponse.json({
      path: filePath,
      content: result.content,
      modified: result.modified,
      readOnly: result.readOnly,
    })
  } catch (err: unknown) {
    // Path traversal attempts from resolveWithin
    if (err instanceof Error && err.message.includes('Path escapes')) {
      return NextResponse.json({ error: 'Invalid file path' }, { status: 400 })
    }
    logger.error({ err }, 'GET /api/agents/[id]/files/[...path] error')
    return NextResponse.json(
      { error: 'Failed to read file' },
      { status: 500 }
    )
  }
}

/**
 * PUT /api/agents/[id]/files/[...path]
 *
 * Saves content to a specific .md file in an agent's workspace.
 * Requires operator role (RBAC gate for writes).
 */
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string; path: string[] }> }
) {
  const auth = requireRole(request, 'operator')
  if ('error' in auth) return NextResponse.json({ error: auth.error }, { status: auth.status })

  const limited = mutationLimiter(request)
  if (limited) return limited

  try {
    const resolvedParams = await params
    const agentId = resolvedParams.id
    const filePath = resolvedParams.path.join('/')

    const snapshot = healthMonitor.getSnapshot()
    const agent = snapshot.find(a => a.id === agentId)
    if (!agent) {
      return NextResponse.json(
        { error: 'Agent not found or not yet discovered' },
        { status: 404 }
      )
    }

    const body = await request.json()
    if (typeof body.content !== 'string') {
      return NextResponse.json(
        { error: 'Request body must include a "content" string' },
        { status: 400 }
      )
    }

    const result = writeMemoryFile(agent.agent.workspacePath, filePath, body.content)

    return NextResponse.json({
      success: true,
      path: filePath,
      modified: result.modified,
    })
  } catch (err: unknown) {
    // Read-only file rejection
    if (err instanceof Error && err.message.includes('read-only')) {
      return NextResponse.json(
        { error: 'File is read-only (auto-generated by agent)' },
        { status: 403 }
      )
    }
    // Path traversal attempts from resolveWithin
    if (err instanceof Error && err.message.includes('Path escapes')) {
      return NextResponse.json({ error: 'Invalid file path' }, { status: 400 })
    }
    logger.error({ err }, 'PUT /api/agents/[id]/files/[...path] error')
    return NextResponse.json(
      { error: 'Failed to write file' },
      { status: 500 }
    )
  }
}
